import Head from 'next/head'
import NavBar from '../components/NavBar'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main  className='bg-cyan-500 h-screen'>
     <NavBar />
      </main>

    </div>
  )
}
