import Head from 'next/head'
import NavBar from '../components/NavBar'
import HomeScreen from '../components/HomeScreen'
import Services from '../components/Services'
import { useState } from 'react'
import Skills from '../components/Skills'
export default function Home() {
  const[darkmode ,setDarkmode] = useState(false)
  return (
    <div>
      <Head>
        <title>Abhishek || Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={darkmode? 'dark' : ''}>
     <NavBar darkmode={darkmode} setDarkmode={setDarkmode}  />
      <HomeScreen />
      <Skills />
      </main>

    </div>
  )
}
